name: ic50-forge
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - jupyter
  - scikit-learn
  - pandas
  - numpy
  - matplotlib
  - rdkit
  - shap
  - streamlit
  - pip
  - pip:
    - seaborn

